import {applyStripeLines} from "../stripe-tax-quote"
import {stripeTaxDefaults} from "../tax"
const quote:any={currency:"gbp",shipping_minor:495,lines:[{variant_id:"v1",unit_minor:1000,quantity:1,recurring:true}],tax_policy:"stripe_default"}
function row(shipping=false,inclusive=false){const amount=shipping?495:1000;const tax=inclusive?(shipping?83:167):(shipping?99:200);return {quantity:1,currency:"gbp",amount_discount:0,amount_tax:tax,amount_total:amount+(inclusive?0:tax),price:{id:shipping?"price_shipping":"price_v1",unit_amount:amount,tax_behavior:inclusive?"inclusive":"exclusive",product:{metadata:shipping?{peptech_shipping:"true"}:{variant_id:"v1",recurring:"true"}}},taxes:[{amount:tax,rate:{id:"txr_1",percentage:20,display_name:"VAT"}}]}}
describe("Stripe tax authority",()=>{
 it("uses Stripe exclusive totals and retains original prices",()=>{const q=applyStripeLines(quote,[row(),row(true)],1794);expect(q.tax_minor).toBe(299);expect(q.total_minor).toBe(1794);expect(q.renewal_minor).toBe(1794);expect(q.lines[0].unit_minor).toBe(1000)})
 it("accepts provider inclusive rounding without recalculating it",()=>{const q=applyStripeLines(quote,[row(false,true),row(true,true)],1495);expect(q.tax_minor).toBe(250);expect(q.total_minor).toBe(1495)})
 it.each(["quantity","price","discount","identity"])("rejects changed %s",change=>{const r=row();if(change==="quantity")r.quantity=2;if(change==="price")r.price.unit_amount=1;if(change==="discount")r.amount_discount=1;if(change==="identity")r.price.product.metadata={variant_id:"another",recurring:"true"};expect(()=>applyStripeLines(quote,[r,row(true)],1794)).toThrow()})
 it("rejects missing lines and mismatched totals",()=>{expect(()=>applyStripeLines(quote,[row()],1200)).toThrow();expect(()=>applyStripeLines(quote,[row(),row(true)],1800)).toThrow()})
 it("uses current invoice taxes with original price IDs",()=>{const saved=applyStripeLines(quote,[row(),row(true)],1794);const rows=[row(),row(true)].map(r=>({quantity:1,currency:"gbp",amount:r.price.unit_amount,pricing:{unit_amount_decimal:String(r.price.unit_amount),price_details:{price:r.price.id}},taxes:r.taxes.map(t=>({...t,tax_behavior:"exclusive"}))}));expect(applyStripeLines(saved,rows,1794,true).total_minor).toBe(1794)})
 it("permits an explicitly labelled unconfigured sandbox but blocks live",async()=>{const stripe={tax:{settings:{retrieve:async()=>({status:"pending",defaults:{}})},registrations:{list:async()=>({data:[]})}}};expect((await stripeTaxDefaults(stripe,"test")).status).toBe("sandbox_unconfigured");await expect(stripeTaxDefaults(stripe,"live")).rejects.toThrow()})
 it("uses the account default behaviour for GBP",async()=>{const stripe={tax:{settings:{retrieve:async()=>({status:"active",defaults:{tax_behavior:"inferred_by_currency",tax_code:"txcd_fixture"}})},registrations:{list:async()=>({data:[{country:"GB"}]})}}};expect(await stripeTaxDefaults(stripe,"test")).toMatchObject({enabled:true,inclusive:true,code:"txcd_fixture"})})
})
